## traefik.yml
# https://doc.traefik.io/traefik/providers/docker/

global:
  checkNewVersion: false
  sendAnonymousUsage: false

# Docker configuration backend
providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.test.net`)"
    exposedByDefault: false
    network: test-net
    swarmMode: false

# API and dashboard configuration
api:
  insecure: true
  debug: true

log:
  level: "debug"

entrypoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  api-server-resolver:
    acme:
      caserver: "https://ca.test.net:9000/acme/acme/directory"
      email: "me@francesco-riosa.com"
      storage: "acme.json"
      httpChallenge:
        # used during the challenge (which is unencrypted)
        entryPoint: "web"
